changed

diff --git a/.github/workflows/CD_Test-Product.yaml b/.github/workflows/CD_Test-Product.yaml
--- a/.github/workflows/CD_Test-Product.yaml
+++ b/.github/workflows/CD_Test-Product.yaml
@@ -64,40 +64,42 @@ jobs:
             --config=../k8s/product/cloudBuild.yaml \
             --async \
             --format='value(metadata.build.id)')
-          echo "🔍 Raw Build Output:"
-          BUILD_OUTPUT=$(gcloud builds log $BUILD_ID --project=levomart)
+      - name: Echo Done
+        run: echo "Done with product Service CI/CD for Test Branch"
+#   echo "🔍 Raw Build Output:"
+# BUILD_OUTPUT=$(gcloud builds log $BUILD_ID --project=levomart)
 
-      # - name: Wait for Cloud Build to Finish
-      #   run: |
-      #     echo "⏳ Waiting for build $BUILD_ID to complete..."
+# - name: Wait for Cloud Build to Finish
+#   run: |
+#     echo "⏳ Waiting for build $BUILD_ID to complete..."
 
-      #     for i in {1..60}; do
-      #       STATUS=$(gcloud builds describe $BUILD_ID --project=levomart --format='value(status)')
-      #       echo "🔁 Build status: $STATUS"
+#     for i in {1..60}; do
+#       STATUS=$(gcloud builds describe $BUILD_ID --project=levomart --format='value(status)')
+#       echo "🔁 Build status: $STATUS"
 
-      #       if [[ "$STATUS" == "SUCCESS" ]]; then
-      #         echo "✅ Build succeeded!"
-      #         exit 0
-      #       elif [[ "$STATUS" == "FAILURE" || "$STATUS" == "CANCELLED" || "$STATUS" == "TIMEOUT" ]]; then
-      #         echo "❌ Build failed with status: $STATUS"
-      #         exit 1
-      #       fi
+#       if [[ "$STATUS" == "SUCCESS" ]]; then
+#         echo "✅ Build succeeded!"
+#         exit 0
+#       elif [[ "$STATUS" == "FAILURE" || "$STATUS" == "CANCELLED" || "$STATUS" == "TIMEOUT" ]]; then
+#         echo "❌ Build failed with status: $STATUS"
+#         exit 1
+#       fi
 
-      #       echo "⏱ Sleeping for 20 seconds..."
-      #       sleep 20
-      #     done
+#       echo "⏱ Sleeping for 20 seconds..."
+#       sleep 20
+#     done
 
-      #     echo "❌ Timed out waiting for build to finish."
-      #     exit 1
+#     echo "❌ Timed out waiting for build to finish."
+#     exit 1
 
-      # - name: Submit Cloud Build using external file
-      #   run: |
-      #     gcloud builds submit \
-      #       --project=levomart \
-      #       --config=../k8s/product/cloudBuild.yaml
+# - name: Submit Cloud Build using external file
+#   run: |
+#     gcloud builds submit \
+#       --project=levomart \
+#       --config=../k8s/product/cloudBuild.yaml
 
-      # - name: Submit Cloud Build
-      #   run: |
-      #     gcloud builds submit auth \
-      #       --tag=asia-south1-docker.pkg.dev/levomart/levomart-repo/auth:$SHORT_SHA \
-      #       --project=levomart
+# - name: Submit Cloud Build
+#   run: |
+#     gcloud builds submit auth \
+#       --tag=asia-south1-docker.pkg.dev/levomart/levomart-repo/auth:$SHORT_SHA \
+#       --project=levomart
